# docker-compose version
version: '3.8'

services:
  postgres:
    image: postgres:17.9-alpine3.23
    container_name: task-pilot-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my-secret-pw
      POSTGRES_DB: task_pilot
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  task-pilot-admin:
    image: ruishan/task-pilot:latest
    container_name: task-pilot-admin
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/task_pilot
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: my-secret-pw
    ports:
      - "8080:8080"
    depends_on:
      - postgres
