-- TASK-PILOT PostgreSQL 初始化脚本

BEGIN;

-- ------------------------------ job group and registry ------------------------------

CREATE TABLE IF NOT EXISTS task_pilot_group (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_name varchar(64) NOT NULL,
    title varchar(12) NOT NULL,
    address_type smallint NOT NULL DEFAULT 0,
    address_list text,
    update_time timestamp
);
COMMENT ON TABLE task_pilot_group IS '执行器分组表';
COMMENT ON COLUMN task_pilot_group.id IS '主键 ID';
COMMENT ON COLUMN task_pilot_group.app_name IS '执行器 AppName';
COMMENT ON COLUMN task_pilot_group.title IS '执行器名称';
COMMENT ON COLUMN task_pilot_group.address_type IS '执行器地址类型：0=自动注册、1=手动录入';
COMMENT ON COLUMN task_pilot_group.address_list IS '执行器地址列表，多地址逗号分隔';
COMMENT ON COLUMN task_pilot_group.update_time IS '更新时间';

CREATE TABLE IF NOT EXISTS task_pilot_registry (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registry_group varchar(50) NOT NULL,
    registry_key varchar(255) NOT NULL,
    registry_value varchar(255) NOT NULL,
    update_time timestamp,
    CONSTRAINT i_g_k_v UNIQUE (registry_group, registry_key, registry_value)
);
COMMENT ON TABLE task_pilot_registry IS '执行器注册表';
COMMENT ON COLUMN task_pilot_registry.id IS '主键 ID';
COMMENT ON COLUMN task_pilot_registry.registry_group IS '注册分组';
COMMENT ON COLUMN task_pilot_registry.registry_key IS '注册 Key';
COMMENT ON COLUMN task_pilot_registry.registry_value IS '注册值';
COMMENT ON COLUMN task_pilot_registry.update_time IS '最近心跳更新时间';

-- ------------------------------ job info ------------------------------

CREATE TABLE IF NOT EXISTS task_pilot_info (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_group integer NOT NULL,
    job_desc varchar(255) NOT NULL,
    add_time timestamp,
    update_time timestamp,
    author varchar(64),
    alarm_email varchar(255),
    schedule_type varchar(50) NOT NULL DEFAULT 'NONE',
    schedule_conf varchar(128),
    misfire_strategy varchar(50) NOT NULL DEFAULT 'DO_NOTHING',
    executor_route_strategy varchar(50),
    executor_handler varchar(255),
    executor_param varchar(512),
    executor_block_strategy varchar(50),
    executor_timeout integer NOT NULL DEFAULT 0,
    executor_fail_retry_count integer NOT NULL DEFAULT 0,
    glue_type varchar(50) NOT NULL,
    glue_source text,
    glue_remark varchar(128),
    glue_updatetime timestamp,
    child_jobid varchar(255),
    trigger_status smallint NOT NULL DEFAULT 0,
    trigger_last_time bigint NOT NULL DEFAULT 0,
    trigger_next_time bigint NOT NULL DEFAULT 0
);
COMMENT ON TABLE task_pilot_info IS '任务定义表';
COMMENT ON COLUMN task_pilot_info.id IS '主键 ID';
COMMENT ON COLUMN task_pilot_info.job_group IS '执行器主键 ID';
COMMENT ON COLUMN task_pilot_info.job_desc IS '任务描述';
COMMENT ON COLUMN task_pilot_info.add_time IS '创建时间';
COMMENT ON COLUMN task_pilot_info.update_time IS '更新时间';
COMMENT ON COLUMN task_pilot_info.author IS '作者';
COMMENT ON COLUMN task_pilot_info.alarm_email IS '报警邮件';
COMMENT ON COLUMN task_pilot_info.schedule_type IS '调度类型';
COMMENT ON COLUMN task_pilot_info.schedule_conf IS '调度配置，值含义取决于调度类型';
COMMENT ON COLUMN task_pilot_info.misfire_strategy IS '调度过期策略';
COMMENT ON COLUMN task_pilot_info.executor_route_strategy IS '执行器路由策略';
COMMENT ON COLUMN task_pilot_info.executor_handler IS '执行器任务 Handler';
COMMENT ON COLUMN task_pilot_info.executor_param IS '执行器任务参数';
COMMENT ON COLUMN task_pilot_info.executor_block_strategy IS '阻塞处理策略';
COMMENT ON COLUMN task_pilot_info.executor_timeout IS '任务执行超时时间，单位秒';
COMMENT ON COLUMN task_pilot_info.executor_fail_retry_count IS '失败重试次数';
COMMENT ON COLUMN task_pilot_info.glue_type IS 'GLUE 类型';
COMMENT ON COLUMN task_pilot_info.glue_source IS 'GLUE 源代码';
COMMENT ON COLUMN task_pilot_info.glue_remark IS 'GLUE 备注';
COMMENT ON COLUMN task_pilot_info.glue_updatetime IS 'GLUE 更新时间';
COMMENT ON COLUMN task_pilot_info.child_jobid IS '子任务 ID，多个逗号分隔';
COMMENT ON COLUMN task_pilot_info.trigger_status IS '调度状态：0=停止，1=运行';
COMMENT ON COLUMN task_pilot_info.trigger_last_time IS '上次调度时间戳（毫秒）';
COMMENT ON COLUMN task_pilot_info.trigger_next_time IS '下次调度时间戳（毫秒）';

CREATE TABLE IF NOT EXISTS task_pilot_logglue (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id integer NOT NULL,
    glue_type varchar(50),
    glue_source text,
    glue_remark varchar(128) NOT NULL,
    add_time timestamp,
    update_time timestamp
);
COMMENT ON TABLE task_pilot_logglue IS 'GLUE 代码变更记录表';
COMMENT ON COLUMN task_pilot_logglue.id IS '主键 ID';
COMMENT ON COLUMN task_pilot_logglue.job_id IS '任务主键 ID';
COMMENT ON COLUMN task_pilot_logglue.glue_type IS 'GLUE 类型';
COMMENT ON COLUMN task_pilot_logglue.glue_source IS 'GLUE 源代码';
COMMENT ON COLUMN task_pilot_logglue.glue_remark IS 'GLUE 备注';
COMMENT ON COLUMN task_pilot_logglue.add_time IS '创建时间';
COMMENT ON COLUMN task_pilot_logglue.update_time IS '更新时间';

-- ------------------------------ job log and report ------------------------------

CREATE TABLE IF NOT EXISTS task_pilot_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_group integer NOT NULL,
    job_id integer NOT NULL,
    executor_address varchar(255),
    executor_handler varchar(255),
    executor_param varchar(512),
    executor_sharding_param varchar(20),
    executor_fail_retry_count integer NOT NULL DEFAULT 0,
    trigger_time timestamp,
    trigger_code integer NOT NULL,
    trigger_msg text,
    handle_time timestamp,
    handle_code integer NOT NULL,
    handle_msg text,
    alarm_status smallint NOT NULL DEFAULT 0
);
COMMENT ON TABLE task_pilot_log IS '任务执行日志表';
COMMENT ON COLUMN task_pilot_log.id IS '主键 ID';
COMMENT ON COLUMN task_pilot_log.job_group IS '执行器主键 ID';
COMMENT ON COLUMN task_pilot_log.job_id IS '任务主键 ID';
COMMENT ON COLUMN task_pilot_log.executor_address IS '本次执行命中的执行器地址';
COMMENT ON COLUMN task_pilot_log.executor_handler IS '执行器任务 Handler';
COMMENT ON COLUMN task_pilot_log.executor_param IS '执行器任务参数';
COMMENT ON COLUMN task_pilot_log.executor_sharding_param IS '执行器任务分片参数，格式如 1/2';
COMMENT ON COLUMN task_pilot_log.executor_fail_retry_count IS '失败重试次数';
COMMENT ON COLUMN task_pilot_log.trigger_time IS '调度时间';
COMMENT ON COLUMN task_pilot_log.trigger_code IS '调度结果码';
COMMENT ON COLUMN task_pilot_log.trigger_msg IS '调度日志';
COMMENT ON COLUMN task_pilot_log.handle_time IS '执行时间';
COMMENT ON COLUMN task_pilot_log.handle_code IS '执行状态码';
COMMENT ON COLUMN task_pilot_log.handle_msg IS '执行日志';
COMMENT ON COLUMN task_pilot_log.alarm_status IS '告警状态：0=默认，1=无需告警，2=告警成功，3=告警失败';

CREATE INDEX IF NOT EXISTS i_trigger_time ON task_pilot_log (trigger_time);
CREATE INDEX IF NOT EXISTS i_handle_code ON task_pilot_log (handle_code);
CREATE INDEX IF NOT EXISTS i_jobid_jobgroup ON task_pilot_log (job_id, job_group);
CREATE INDEX IF NOT EXISTS i_job_id ON task_pilot_log (job_id);

CREATE TABLE IF NOT EXISTS task_pilot_log_report (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trigger_day timestamp,
    running_count integer NOT NULL DEFAULT 0,
    suc_count integer NOT NULL DEFAULT 0,
    fail_count integer NOT NULL DEFAULT 0,
    update_time timestamp,
    CONSTRAINT i_trigger_day UNIQUE (trigger_day)
);
COMMENT ON TABLE task_pilot_log_report IS '任务日志日报表';
COMMENT ON COLUMN task_pilot_log_report.id IS '主键 ID';
COMMENT ON COLUMN task_pilot_log_report.trigger_day IS '统计日期';
COMMENT ON COLUMN task_pilot_log_report.running_count IS '运行中日志数量';
COMMENT ON COLUMN task_pilot_log_report.suc_count IS '执行成功日志数量';
COMMENT ON COLUMN task_pilot_log_report.fail_count IS '执行失败日志数量';
COMMENT ON COLUMN task_pilot_log_report.update_time IS '更新时间';

-- ------------------------------ lock ------------------------------

CREATE TABLE IF NOT EXISTS task_pilot_lock (
    lock_name varchar(50) PRIMARY KEY
);
COMMENT ON TABLE task_pilot_lock IS '调度锁表';
COMMENT ON COLUMN task_pilot_lock.lock_name IS '锁名称';

-- ------------------------------ user ------------------------------

CREATE TABLE IF NOT EXISTS task_pilot_user (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(50) NOT NULL,
    password varchar(100) NOT NULL,
    token varchar(100),
    role smallint NOT NULL,
    permission varchar(255),
    CONSTRAINT i_username UNIQUE (username)
);
COMMENT ON TABLE task_pilot_user IS '用户表';
COMMENT ON COLUMN task_pilot_user.id IS '主键 ID';
COMMENT ON COLUMN task_pilot_user.username IS '账号';
COMMENT ON COLUMN task_pilot_user.password IS '密码加密信息';
COMMENT ON COLUMN task_pilot_user.token IS '登录 Token';
COMMENT ON COLUMN task_pilot_user.role IS '角色：0=普通用户，1=管理员';
COMMENT ON COLUMN task_pilot_user.permission IS '权限：执行器 ID 列表，多个逗号分隔';

-- ------------------------------ default data ------------------------------

INSERT INTO task_pilot_group (id, app_name, title, address_type, address_list, update_time)
VALUES
    (1, 'task-pilot-executor-sample', '通用执行器Sample', 0, NULL, now()),
    (2, 'task-pilot-executor-sample-ai', 'AI执行器Sample', 0, NULL, now())
ON CONFLICT (id) DO NOTHING;

INSERT INTO task_pilot_info (
    id,
    job_group,
    job_desc,
    add_time,
    update_time,
    author,
    alarm_email,
    schedule_type,
    schedule_conf,
    misfire_strategy,
    executor_route_strategy,
    executor_handler,
    executor_param,
    executor_block_strategy,
    executor_timeout,
    executor_fail_retry_count,
    glue_type,
    glue_source,
    glue_remark,
    glue_updatetime,
    child_jobid
)
VALUES
    (1, 1, '示例任务01', now(), now(), 'TASK-PILOT', '', 'CRON', '0 0 0 * * ? *',
     'DO_NOTHING', 'FIRST', 'demoJobHandler', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化',
     now(), ''),
    (2, 2, 'Ollama示例任务01', now(), now(), 'TASK-PILOT', '', 'NONE', '',
     'DO_NOTHING', 'FIRST', 'ollamaJobHandler', '{
    "input": "慢SQL问题分析思路",
    "prompt": "你是一个研发工程师，擅长解决技术类问题。",
    "model": "qwen3:0.6b"
}', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化',
     now(), ''),
    (3, 2, 'Dify示例任务', now(), now(), 'TASK-PILOT', '', 'NONE', '',
     'DO_NOTHING', 'FIRST', 'difyWorkflowJobHandler', '{
    "inputs":{
        "input":"查询班级各学科前三名"
    },
    "user": "task-pilot",
    "baseUrl": "http://localhost/v1",
    "apiKey": "app-OUVgNUOQRIMokfmuJvBJoUTN"
}', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化',
     now(), '')
ON CONFLICT (id) DO NOTHING;

INSERT INTO task_pilot_user (id, username, password, role, permission)
VALUES (1, 'admin', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 1, NULL)
ON CONFLICT (id) DO NOTHING;

INSERT INTO task_pilot_lock (lock_name)
VALUES ('schedule_lock')
ON CONFLICT (lock_name) DO NOTHING;

-- 显式写入种子主键后，同步 identity 序列，避免后续插入撞号。
SELECT setval(pg_get_serial_sequence('task_pilot_group', 'id'), (SELECT MAX(id) FROM task_pilot_group), true);
SELECT setval(pg_get_serial_sequence('task_pilot_info', 'id'), (SELECT MAX(id) FROM task_pilot_info), true);
SELECT setval(pg_get_serial_sequence('task_pilot_user', 'id'), (SELECT MAX(id) FROM task_pilot_user), true);

COMMIT;
